package Gui;

import Controler.*;
import javax.swing.*;

/**
 *
 * @author manolias
 */
public class Interface extends javax.swing.JFrame {

	/**
	 * Creates new form Interface
	 */
	private Controle c;
	private DefaultListModel modeList = new DefaultListModel();

	public Interface(Controle c) {
		this.addWindowListener(c);
		this.c = c;
		initComponents();
		this.setVisible(true);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	private void initComponents() {

		jLabel3 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		remoteTextField = new javax.swing.JTextField();
		disconnectButton = new javax.swing.JButton();
		sendButton = new javax.swing.JButton();
		jScrollPane4 = new javax.swing.JScrollPane();
		messageTextArea = new javax.swing.JTextArea();
		jScrollPane5 = new javax.swing.JScrollPane();
		conversationTextArea = new javax.swing.JTextArea();
		jLabel5 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		usernameLabel = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		setUsersList(new javax.swing.JList());

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setBackground(new java.awt.Color(255, 102, 255));

		jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
		jLabel3.setText("Send message to :");

		jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
		jLabel2.setText("Brothers connected :");

		jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
		jLabel4.setText("Conversation : ");

		disconnectButton.setText("Disconnect");

		sendButton.setText("Send");
		sendButton.addActionListener(c);

		messageTextArea.setColumns(20);
		messageTextArea.setRows(5);
		jScrollPane4.setViewportView(messageTextArea);

		conversationTextArea.setEditable(false);
		conversationTextArea.setColumns(20);
		conversationTextArea.setRows(5);
		jScrollPane5.setViewportView(conversationTextArea);

		jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		jLabel5.setText("You're now connected with the whole world,");

		jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

		usernameLabel.setFont(new java.awt.Font("AR HERMANN", 1, 24)); // NOI18N
		usernameLabel.setText("  ");

		getUsersList().setModel(modeList);
		jScrollPane1.setViewportView(getUsersList());

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
						layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGroup(layout.createSequentialGroup()
						.addComponent(jLabel5)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(usernameLabel)
						.addComponent(jLabel1))))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addGroup(layout.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
						.addGap(118, 118, 118)
						.addComponent(jLabel4)
						.addGap(131, 131, 131))
						.addGroup(layout.createSequentialGroup()
						.addGap(52, 52, 52)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
						.addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGroup(layout.createSequentialGroup()
						.addComponent(jLabel3)
						.addGap(33, 33, 33)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(remoteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))))))
						.addGap(28, 28, 28))))
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
						.addGap(90, 90, 90)
						.addComponent(disconnectButton)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(sendButton)
						.addGap(189, 189, 189)));
		layout.setVerticalGroup(
						layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
						.addGap(67, 67, 67)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel4)))
						.addGroup(layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(usernameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(jLabel5)
						.addComponent(jLabel1)))))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(remoteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel3))
						.addGap(18, 18, 18)
						.addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
						.addGap(27, 27, 27)
						.addComponent(sendButton))
						.addGroup(layout.createSequentialGroup()
						.addGap(18, 18, 18)
						.addComponent(disconnectButton)))
						.addContainerGap(24, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>                        

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				//new Interface().setVisible(true);
			}
		});
	}
	// Variables declaration - do not modify                     
	private javax.swing.JTextArea conversationTextArea;
	private javax.swing.JButton disconnectButton;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane4;
	private javax.swing.JScrollPane jScrollPane5;
	private javax.swing.JTextArea messageTextArea;
	private javax.swing.JTextField remoteTextField;
	private javax.swing.JButton sendButton;
	private javax.swing.JLabel usernameLabel;
	private javax.swing.JList usersList;
	// End of variables declaration                   

	/**
	 * @return the sendButton
	 */
	public javax.swing.JButton getSendButton() {
		return sendButton;
	}

	/**
	 * @param sendButton the sendButton to set
	 */
	public void setSendButton(javax.swing.JButton sendButton) {
		this.sendButton = sendButton;
	}

	/**
	 * @return the usersTextArea
	 */
	/**
	 * @param usersTextArea the usersTextArea to set
	 */
	/**
	 * @return the disconnectButton
	 */
	public javax.swing.JButton getDisconnectButton() {
		return disconnectButton;
	}

	/**
	 * @param disconnectButton the disconnectButton to set
	 */
	public void setDisconnectButton(javax.swing.JButton disconnectButton) {
		this.disconnectButton = disconnectButton;
	}

	/**
	 * @return the messageTextArea
	 */
	public javax.swing.JTextArea getMessageTextArea() {
		return messageTextArea;
	}

	/**
	 * @param messageTextArea the messageTextArea to set
	 */
	public void setMessageTextArea(javax.swing.JTextArea messageTextArea) {
		this.messageTextArea = messageTextArea;
	}

	/**
	 * @return the conversationTextArea
	 */
	public javax.swing.JTextArea getConversationTextArea() {
		return conversationTextArea;
	}

	/**
	 * @param conversationTextArea the conversationTextArea to set
	 */
	public void setConversationTextArea(javax.swing.JTextArea conversationTextArea) {
		this.conversationTextArea = conversationTextArea;
	}

	/**
	 * @return the remoteTextField
	 */
	public javax.swing.JTextField getRemoteTextField() {
		return remoteTextField;
	}

	/**
	 * @param remoteTextField the remoteTextField to set
	 */
	public void setRemoteTextField(String s) {
		this.remoteTextField.setText(s);
	}

	/**
	 * @return the usernameLabel
	 */
	public javax.swing.JLabel getUsernameLabel() {
		return usernameLabel;
	}

	/**
	 * @param usernameLabel the usernameLabel to set
	 */
	public void setUsernameLabel(javax.swing.JLabel usernameLabel) {
		this.usernameLabel = usernameLabel;


	}

	public String getUserSelected() {
		return this.getUsersList().getSelectedValue().toString();
	}

	public void addRemoteUser(String newU) {
		//System.out.println(newU);
		this.modeList.addElement(newU);
	}

	/**
	 * @return the usersList
	 */
	public javax.swing.JList getUsersList() {
		return usersList;
	}

	/**
	 * @param usersList the usersList to set
	 */
	public void setUsersList(javax.swing.JList usersList) {
		this.usersList = usersList;
		usersList.addMouseListener(c);
	}
}
