/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import Controler.Controle;
import javax.swing.DefaultListModel;

/**
 *
 * @author Alexandre
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    private Controle c;
	private DefaultListModel modeList = new DefaultListModel();

	public Interface(Controle c) {
		this.addWindowListener(c);
		this.c = c;
		initComponents();
		this.setVisible(true);
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    sendButton = new javax.swing.JButton();
    jScrollPane4 = new javax.swing.JScrollPane();
    messageTextArea = new javax.swing.JTextArea();
    remoteTextField = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    jScrollPane5 = new javax.swing.JScrollPane();
    conversationTextArea = new javax.swing.JTextArea();
    jScrollPane1 = new javax.swing.JScrollPane();
    usersList = new javax.swing.JList();
    jLabel4 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    fileButton = new javax.swing.JButton();
    disconnectButton = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    sendButton.setText("Send");
    sendButton.addActionListener(c);

    messageTextArea.setColumns(20);
    messageTextArea.setRows(5);
    jScrollPane4.setViewportView(messageTextArea);

    jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
    jLabel3.setText("Send message to");

    conversationTextArea.setEditable(false);
    conversationTextArea.setColumns(20);
    conversationTextArea.setRows(5);
    jScrollPane5.setViewportView(conversationTextArea);

    usersList.setModel(modeList);
    usersList.addMouseListener(c);
    jScrollPane1.setViewportView(usersList);

    jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
    jLabel4.setText("Conversation ");

    jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
    jLabel2.setText("Users connected");

    fileButton.setText("File");
    fileButton.addActionListener(c);

    disconnectButton.setText("Disconnect");
    disconnectButton.addActionListener(c);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(112, 112, 112))
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 57, Short.MAX_VALUE))))
          .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(jLabel3)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(remoteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addGap(12, 12, 12)
            .addComponent(disconnectButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(45, 45, 45)
            .addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGap(52, 52, 52))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel4))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
          .addComponent(jScrollPane5))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(remoteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel3))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(fileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(disconnectButton))
        .addGap(12, 12, 12))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Interface().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextArea conversationTextArea;
  private javax.swing.JButton disconnectButton;
  private javax.swing.JButton fileButton;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane4;
  private javax.swing.JScrollPane jScrollPane5;
  private javax.swing.JTextArea messageTextArea;
  private javax.swing.JTextField remoteTextField;
  private javax.swing.JButton sendButton;
  private javax.swing.JList usersList;
  // End of variables declaration//GEN-END:variables

/**
	 * @return the sendButton
	 */
	public javax.swing.JButton getSendButton() {
		return sendButton;
	}

	/**
	 * @param sendButton the sendButton to set
	 */
	public void setSendButton(javax.swing.JButton sendButton) {
		this.sendButton = sendButton;
	}

	/**
	 * @return the usersTextArea
	 */
	/**
	 * @param usersTextArea the usersTextArea to set
	 */
	/**
	 * @return the disconnectButton
	 */
	public javax.swing.JButton getDisconnectButton() {
		return disconnectButton;
	}

	/**
	 * @param disconnectButton the disconnectButton to set
	 */
	public void setDisconnectButton(javax.swing.JButton disconnectButton) {
		this.disconnectButton = disconnectButton;
	}

	/**
	 * @return the messageTextArea
	 */
	public javax.swing.JTextArea getMessageTextArea() {
		return messageTextArea;
	}

	/**
	 * @param messageTextArea the messageTextArea to set
	 */
	public void setMessageTextArea(javax.swing.JTextArea messageTextArea) {
		this.messageTextArea = messageTextArea;
	}

	/**
	 * @return the conversationTextArea
	 */
	public javax.swing.JTextArea getConversationTextArea() {
		return conversationTextArea;
	}

	/**
	 * @param conversationTextArea the conversationTextArea to set
	 */
	public void setConversationTextArea(javax.swing.JTextArea conversationTextArea) {
		this.conversationTextArea = conversationTextArea;
	}

	/**
	 * @return the remoteTextField
	 */
	public javax.swing.JTextField getRemoteTextField() {
		return remoteTextField;
	}

	/**
	 * @param remoteTextField the remoteTextField to set
	 */
	public void setRemoteTextField(String s) {
		this.remoteTextField.setText(s);
	}

	/**
	 * @return the usernameLabel
	 */
	public String getUserSelected() {
		return this.getUsersList().getSelectedValue().toString();
	}

	public void addRemoteUser(String newU) {
		//System.out.println(newU);
		this.modeList.addElement(newU);
	}
        
        public void removeRemoteUser(String rU){
            this.modeList.removeElement(rU);
            //System.out.println("user removed");
        }

	/**
	 * @return the usersList
	 */
	public javax.swing.JList getUsersList() {
		return usersList;
	}

	/**
	 * @param usersList the usersList to set
	 */
	public void setUsersList(javax.swing.JList usersList) {
		this.usersList = usersList;
		usersList.addMouseListener(c);
	}

    /**
     * @return the fileButton
     */
    public javax.swing.JButton getFileButton() {
        return fileButton;
    }

    /**
     * @param fileButton the fileButton to set
     */
    public void setFileButton(javax.swing.JButton fileButton) {
        this.fileButton = fileButton;
    }
}
